# The Numpy Module

## Creating a Numpy array

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
print(arr)

[1 2 3 4 5]


In [7]:
#Shows type of data that my array holds
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
#Shows current version of numpy present in my system
print(np.__version__)

1.21.5


In [10]:
#Creates a 0-D array
arr = np.array(42)

In [11]:
print(arr)

42


In [12]:
#Creates a 1-D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [13]:
#Creates a 2-D array
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [14]:
#Creates a 3-D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
#to check number of dimensions
print(arr.ndim) #prints 0
print(arr1.ndim) #prints 1
print(arr2.ndim) #prints 2
print(arr3.ndim) #prints 3

0
1
2
3


In [17]:
#to initialize an array by specifying the dimensions in the np.array() function
arr4 = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr4) #prints an array of dimension 5

[[[[[1 2 3 4 5]]]]]


# Accessing Array elements

In [18]:
print(arr1[0]) #prints first element of arr1
print(arr1[1]) #prints second element of arr2

1
2


#### Accessing 2-D arrays

In [19]:
print(arr2[0, 1]) #arrayName[rowno, colno]

2


#### Accessing 3-D arrays

In [20]:
print(arr3[0, 1, 2]) # Access the third element of the second array of the first array

6


#### Negative array indexing

In [27]:
print(arr1[-1])

5


# Array Slicing

In [23]:
print(arr1[1:4])

[2 3 4]


In [24]:
print(arr1[:4])

[1 2 3 4]


In [25]:
print(arr1[4:])

[5]


In [28]:
print(arr1[-3:-1])

[3 4]


In [30]:
print(arr1[1:5:2]) #arrayName[start:stop:step]

[2 4]


In [31]:
print(arr2[0:2, 1:4])

[[2 3 4]
 [2 3 4]]


# Numpy Datatypes

In [32]:
#Returns data type of arr1
print(arr1.dtype)

int32


In [33]:
#Creating an array with data type specified
arr5 = np.array([1, 2, 3, 4, 5], dtype='S')
print(arr5.dtype)

|S1


In [34]:
#Converting data type of arr5 from string to integer
newarr = arr5.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4 5]
int32


# Copying and viewing an array

In [35]:
#Copying an array
x = arr1.copy()
print(x)

[1 2 3 4 5]


In [36]:
#Viewing the array
y = arr1.view()
print(y)

[1 2 3 4 5]


In [37]:
#the base attribute checks whether the array owns the data or not 
#If it returns None that means the array owns the data
print(x.base)

None


In [38]:
print(y.base)

[1 2 3 4 5]


# Shape of numpy array

In [39]:
print(arr1.shape)

(5,)


In [40]:
print(arr2.shape)

(2, 5)


In [41]:
print(arr3.shape)

(2, 2, 3)


In [42]:
print(arr4.shape)

(1, 1, 1, 1, 5)


# Flattening array

In [50]:
print(arr2.reshape(-1))

[1 2 3 4 5 1 2 3 4 5]


# Iterating over the array

### For 2-D arrays

In [51]:
for x in arr2:
    print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [52]:
for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
1
2
3
4
5


### Iterating over 3-D arrays

In [53]:
for x in arr3:
    print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [54]:
for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
1
2
3
4
5
6


In [56]:
for x in np.nditer(arr2):
    print(x)

1
2
3
4
5
1
2
3
4
5


In [58]:
for x in np.nditer(arr2, flags = ['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'1'
b'2'
b'3'
b'4'
b'5'


In [59]:
#iterate through every scalar element of the 2D array skipping 1 element
for x in np.nditer(arr2[:,::2]):
    print(x)

1
3
5
1
3
5


In [61]:
#Iteration using the ndenumerate() function
for idx, x in np.ndenumerate(arr2):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 1
(1, 1) 2
(1, 2) 3
(1, 3) 4
(1, 4) 5


# Joining of arrays in numpy

In [64]:
arr6 = np.array([6, 7, 8, 9, 10])
arr7 = np.concatenate((arr1, arr6))
print(arr7)

[ 1  2  3  4  5  6  7  8  9 10]


In [68]:
#Concatenates along rows
arr7 = np.array([[1, 2, 3], [4, 5, 6]])
arr8 = np.concatenate((arr2, arr7), axis = 1)
print(arr8)

[[1 2 3 4 5 1 2 3]
 [1 2 3 4 5 4 5 6]]


In [69]:
#Stacking along rows
arr9 = np.hstack((arr2, arr7))
print(arr9)

[[1 2 3 4 5 1 2 3]
 [1 2 3 4 5 4 5 6]]


In [71]:
#Stacking along columns
arr10 = np.vstack((arr1, arr6))
print(arr10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [72]:
#Stacking along depth
arr11 = np.dstack((arr1, arr6))
print(arr11)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


# Spiliting numpy arrays

In [73]:
#Splits array into 3 parts
new__arr = np.array_split(arr1, 3)
print(new__arr)

[array([1, 2]), array([3, 4]), array([5])]


In [74]:
#splits array into 4 parts
newarra = np.array_split(arr1, 4)
print(newarra)

[array([1, 2]), array([3]), array([4]), array([5])]


# Splitting in arrays 

In [80]:
arr12 = np.array([1, 2, 3, 4])
x = np.where(arr12 == 4) #Returns the position where value is 4
print(x)

(array([3], dtype=int64),)


In [82]:
#searching in sorted arrays
y = np.searchsorted(arr12, 3)
print(y)

2


In [83]:
z = np.searchsorted(arr12, 3, side='right')
print(z)

3


# Sorting in arrays

In [84]:
arr13 = np.array([3, 5, 8, 9, 1])
print(np.sort(arr13))

[1 3 5 8 9]
